version: '3.9'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      spring.datasource.url: jdbc:postgresql://db:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - ${APP_PORT}:8080
    networks:
      - backend
    restart: always

  db:
    container_name: db
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  backend:
    name: app-network

volumes:
  db-data: