create table receipt.public.card
(
    id integer generated by default as identity primary key,
    name varchar(255) not null unique
);

create table receipt.public.cashbox
(
    id integer generated by default as identity primary key
);

create table receipt.public.product
(
    id integer generated by default as identity primary key,
    name varchar(255) not null unique,
    price numeric(6, 2) not null
);

create table receipt.public.promotion
(
    id integer generated by default as identity primary key,
    name varchar(255) not null unique,
    is_active boolean not null,
    percent float4 not null
);

create table receipt.public.promotion_card
(
    promotions_id integer not null references receipt.public.promotion on delete cascade,
    cards_id integer not null references receipt.public.card on delete cascade,
    primary key (promotions_id, cards_id)
);

create table receipt.public.promotion_product
(
    promotions_id integer not null references receipt.public.promotion on delete cascade,
    products_id integer not null references receipt.public.product on delete cascade,
    primary key (promotions_id, products_id)
);

create table receipt.public.receipt
(
    id integer generated by default as identity primary key,
    info varchar(255) not null,
    cashbox_id integer not null references receipt.public.cashbox,
    date date not null,
    time time not null,
    card_id integer references receipt.public.card,
    total numeric(9, 2)                                                      -- not null?
);

create table receipt.public.purchase
(
    id integer generated by default as identity primary key,
    product_id integer not null references receipt.public.product,
    quantity integer not null,
    cost numeric(8, 2),                                                      -- not null?
    receipt_id integer not null references receipt.public.receipt on delete cascade
);

create table receipt.public.receipt_promotion
(
    receipt_id integer not null references receipt.public.receipt on delete cascade,
    promotions_id integer not null unique references receipt.public.promotion on delete cascade,
    primary key (receipt_id, promotions_id)
);
