create table receipt.public.card
(
    id integer generated by default as identity primary key,
    name varchar(255) not null unique
);

create table receipt.public.cashbox
(
    id integer generated by default as identity primary key
);

create table receipt.public.product
(
    id integer generated by default as identity primary key,
    name varchar(255) not null unique,
    price numeric(6, 2) not null
);

create table receipt.public.promotion
(
    id integer generated by default as identity primary key,
    name varchar(255) not null unique,
    is_active boolean not null,
    percent float4 not null
);

create table receipt.public.promotion_card
(
    promotion_id integer not null references receipt.public.promotion on delete cascade,
    card_id integer not null references receipt.public.card on delete cascade,
    primary key (promotion_id, card_id)
);

create table receipt.public.promotion_product
(
    promotion_id integer not null references receipt.public.promotion on delete cascade,
    product_id integer not null references receipt.public.product on delete cascade,
    primary key (promotion_id, product_id)
);

create table receipt.public.orders
(
    id integer generated by default as identity primary key,
    card_id integer references receipt.public.card,
    total numeric(8,2)
);

create table receipt.public.item
(
    id integer generated by default as identity primary key,
    order_id integer not null references receipt.public.orders,
    product_id integer not null references receipt.public.product,
    quantity integer not null
);

create table receipt.public.receipt
(
    id integer generated by default as identity primary key,
    cashbox_id integer not null references receipt.public.cashbox,
    info varchar(255) not null,
    date_time timestamp(0) not null,
    order_id integer not null unique references receipt.public.orders
);
